// Generated by CoffeeScript 1.3.3
(function() {
  var ActivityFeeds;

  ActivityFeeds = (function() {

    function ActivityFeeds(client) {
      this.client = client;
    }

    return ActivityFeeds;

  })();

  module.exports = ActivityFeeds;

}).call(this);
