// Generated by CoffeeScript 1.3.3
(function() {
  var auth, qs, request, url;

  request = require('request');

  url = require('url');

  qs = require('querystring');

  auth = module.exports = {
    config: function(options) {
      this.options = options;
      return this;
    },
    getAuthUrl: function(scopes) {
      var uri;
      uri = REQ_TOKEN_URL;
      uri += '?client_id=' + this.options.id;
      if (scopes != null) {
        uri += '&scope=' + scopes.join(',');
      }
      return uri += '&response_type=code';
    },
    getAccessToken: function(code, callback) {
      return request({
        url: ACCESS_TOKEN_URL,
        method: 'POST',
        body: qs.stringify({
          code: code,
          client_id: this.options.id,
          client_secret: this.options.secret,
          grant_type: 'authorization_code'
        }),
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'User-Agent': 'angelnode/0.0.1 (https://github.com/jaipandya/angelnode) terminal/0.0'
        }
      }, function(err, res, body) {
        if (res.statusCode === 404) {
          return callback(new Error('Access token not found'));
        } else {
          body = qs.parse(body);
          if (body.error) {
            return callback(new Error(body.error));
          } else {
            return callback(null, body.access_token);
          }
        }
      });
    }
  };

}).call(this);
