// Generated by CoffeeScript 1.3.3
(function() {
  var Client, request;

  request = require('request');

  Client = (function() {

    function Client(token) {
      this.token = token;
    }

    return Client;

  })();

  module.exports = function(token) {
    return new Client(token);
  };

}).call(this);
