// Generated by CoffeeScript 1.3.3
(function() {
  var Follows;

  Follows = (function() {

    function Follows(client) {
      this.client = client;
    }

    return Follows;

  })();

  module.exports = Follows;

}).call(this);
