// Generated by CoffeeScript 1.3.3
(function() {
  var Jobs;

  Jobs = (function() {

    function Jobs(client) {
      this.client = client;
    }

    return Jobs;

  })();

  module.exports = Jobs;

}).call(this);
