// Generated by CoffeeScript 1.3.3
(function() {
  var Messages;

  Messages = (function() {

    function Messages(client) {
      this.client = client;
    }

    return Messages;

  })();

  module.exports = Messages;

}).call(this);
