// Generated by CoffeeScript 1.3.3
(function() {
  var Paths;

  Paths = (function() {

    function Paths(client) {
      this.client = client;
    }

    Paths.prototype.responseHandler = function(errMessage, callback) {
      if (errMessage == null) {
        errMessage = 'Error';
      }
      return function(err, statusCode, responseBody) {
        if (err) {
          return callback(err);
        }
        if (statusCode !== 200) {
          return callback(new Error(errMessage));
        } else {
          return callback(null, responseBody);
        }
      };
    };

    Paths.prototype.get = function(options, callback) {
      if (this.client.token == null) {
        return callback(new Error('No token provided, method requires authentication'));
      }
      return this.client.get("/paths", options, this.responseHandler("Paths get error", callback));
    };

    return Paths;

  })();

  module.exports = Paths;

}).call(this);
