// Generated by CoffeeScript 1.3.3
(function() {
  var Paths;

  Paths = (function() {

    function Paths(client) {
      this.client = client;
    }

    return Paths;

  })();

  module.exports = Paths;

}).call(this);
