// Generated by CoffeeScript 1.3.3
(function() {
  var Press;

  Press = (function() {

    function Press(client) {
      this.client = client;
    }

    return Press;

  })();

  module.exports = Press;

}).call(this);
