// Generated by CoffeeScript 1.3.3
(function() {
  var Reviews;

  Reviews = (function() {

    function Reviews(client) {
      this.client = client;
    }

    return Reviews;

  })();

  module.exports = Reviews;

}).call(this);
