// Generated by CoffeeScript 1.3.3
(function() {
  var Search;

  Search = (function() {

    function Search(client) {
      this.client = client;
    }

    return Search;

  })();

  module.exports = Search;

}).call(this);
