// Generated by CoffeeScript 1.3.3
(function() {
  var Startups;

  Startups = (function() {

    function Startups(client) {
      this.client = client;
    }

    return Startups;

  })();

  module.exports = Startups;

}).call(this);
