// Generated by CoffeeScript 1.3.3
(function() {
  var StartupRoles;

  StartupRoles = (function() {

    function StartupRoles(client) {
      this.client = client;
    }

    StartupRoles.prototype.responseHandler = function(errMessage, callback) {
      if (errMessage == null) {
        errMessage = 'Error';
      }
      return function(err, statusCode, responseBody) {
        if (err) {
          return callback(err);
        }
        if (statusCode !== 200) {
          return callback(new Error(errMessage));
        } else {
          return callback(null, responseBody);
        }
      };
    };

    StartupRoles.prototype.get = function(options, callback) {
      return this.client.get("/startup_roles", options, this.responseHandler("Startup role get error", callback));
    };

    return StartupRoles;

  })();

  module.exports = StartupRoles;

}).call(this);
