// Generated by CoffeeScript 1.3.3
(function() {
  var StartupRoles;

  StartupRoles = (function() {

    function StartupRoles(client) {
      this.client = client;
    }

    return StartupRoles;

  })();

  module.exports = StartupRoles;

}).call(this);
