// Generated by CoffeeScript 1.3.3
(function() {
  var StatusUpdates;

  StatusUpdates = (function() {

    function StatusUpdates(client) {
      this.client = client;
    }

    return StatusUpdates;

  })();

  module.exports = StatusUpdates;

}).call(this);
