// Generated by CoffeeScript 1.3.3
(function() {
  var Tags;

  Tags = (function() {

    function Tags(client) {
      this.client = client;
    }

    return Tags;

  })();

  module.exports = Tags;

}).call(this);
