// Generated by CoffeeScript 1.3.3
(function() {
  var AngelNode;

  AngelNode = module.exports = {
    auth: require('./angelnode/auth'),
    client: require('./angelnode/client')
  };

}).call(this);
