// Generated by CoffeeScript 1.3.3
(function() {
  var ACCESS_TOKEN_URL, API_BASE_URL, REQ_TOKEN_URL, angelnode;

  API_BASE_URL = 'https://api.angel.co/1';

  REQ_TOKEN_URL = 'https://angel.co/api/oauth/authorize';

  ACCESS_TOKEN_URL = 'https://angel.co/api/oauth/token';

  angelnode = module.exports = {
    auth: require('./angelnode/auth'),
    client: require('./angelnode/client')
  };

}).call(this);
